version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - emmonsha_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: emmonsha.online_frontend_image
    networks:
      - emmonsha_network
    environment:
      NODE_ENV: ${NODE_ENV:-production}

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - emmonsha_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  pg_data:
  frontend_node_modules:

networks:
  emmonsha_network:
    driver: bridge
